-- ============================================================
-- 월간 메뉴판 노출 이력 및 월별 생성 제한
-- ============================================================

CREATE TABLE IF NOT EXISTS public.monthly_menu_usage (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  source_month       date NOT NULL,
  prompt_seen_at     timestamptz,
  generation_count   smallint NOT NULL DEFAULT 0
                     CHECK (generation_count BETWEEN 0 AND 2),
  last_generated_at  timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, source_month),
  CHECK (source_month = date_trunc('month', source_month)::date)
);

CREATE INDEX IF NOT EXISTS idx_monthly_menu_usage_user_month
  ON public.monthly_menu_usage(user_id, source_month DESC);

ALTER TABLE public.monthly_menu_usage ENABLE ROW LEVEL SECURITY;

-- 기존 공용 함수에 의존하지 않고 이 테이블 전용 함수를 사용한다.
CREATE OR REPLACE FUNCTION public.set_monthly_menu_usage_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_monthly_menu_usage_updated_at
  BEFORE UPDATE ON public.monthly_menu_usage
  FOR EACH ROW EXECUTE FUNCTION public.set_monthly_menu_usage_updated_at();

-- 사용자는 본인 사용량만 읽을 수 있다. 생성 횟수와 노출 이력 변경은
-- 아래 SECURITY DEFINER 함수로만 허용한다.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'monthly_menu_usage'
      AND policyname = 'monthly_menu_usage_select'
  ) THEN
    CREATE POLICY "monthly_menu_usage_select"
      ON public.monthly_menu_usage
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  -- 이전 실행에서 생성됐을 수 있는 쓰기 정책은 삭제하지 않고 무효화한다.
  IF EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'monthly_menu_usage'
      AND policyname = 'monthly_menu_usage_insert'
  ) THEN
    ALTER POLICY "monthly_menu_usage_insert"
      ON public.monthly_menu_usage
      WITH CHECK (false);
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'monthly_menu_usage'
      AND policyname = 'monthly_menu_usage_update'
  ) THEN
    ALTER POLICY "monthly_menu_usage_update"
      ON public.monthly_menu_usage
      USING (false)
      WITH CHECK (false);
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_monthly_menu_generation(p_source_month date)
RETURNS smallint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  next_count smallint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication_required';
  END IF;

  INSERT INTO public.monthly_menu_usage (
    user_id,
    source_month,
    generation_count,
    last_generated_at
  )
  VALUES (
    auth.uid(),
    date_trunc('month', p_source_month)::date,
    1,
    now()
  )
  ON CONFLICT (user_id, source_month)
  DO UPDATE SET
    generation_count = public.monthly_menu_usage.generation_count + 1,
    last_generated_at = now()
  WHERE public.monthly_menu_usage.generation_count < 2
  RETURNING generation_count INTO next_count;

  IF next_count IS NULL THEN
    RAISE EXCEPTION 'monthly_menu_limit_reached';
  END IF;

  RETURN next_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_monthly_menu_prompt_seen(p_source_month date)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'authentication_required';
  END IF;

  INSERT INTO public.monthly_menu_usage (
    user_id,
    source_month,
    prompt_seen_at
  )
  VALUES (
    auth.uid(),
    date_trunc('month', p_source_month)::date,
    now()
  )
  ON CONFLICT (user_id, source_month)
  DO UPDATE SET
    prompt_seen_at = COALESCE(
      public.monthly_menu_usage.prompt_seen_at,
      EXCLUDED.prompt_seen_at
    );
END;
$$;

REVOKE ALL ON FUNCTION public.claim_monthly_menu_generation(date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_monthly_menu_prompt_seen(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claim_monthly_menu_generation(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_monthly_menu_prompt_seen(date) TO authenticated;
